---
apiVersion: v1
kind: Service
metadata:
  name: bw-srv
  labels:
    type: bw-type
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    type: bw-type
